Repository UKHO/ais-service, pull requests merged in 2019-08, with the labels that each got.

#105 Remove automation of resampling
  build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  deployment/src/main/terraform/main.tf
  deployment/src/main/terraform/modules/functions/trigger_resample_function.tf
  deployment/src/main/terraform/modules/functions/variables.tf
  deployment/src/main/terraform/modules/messaging/new-partitioned-file-queue.tf
  deployment/src/main/terraform/modules/messaging/outputs.tf
  deployment/src/main/terraform/modules/messaging/queue/main.tf
  deployment/src/main/terraform/modules/messaging/queue/outputs.tf
  deployment/src/main/terraform/modules/messaging/queue/variables.tf
  deployment/src/main/terraform/modules/messaging/sources/storage_file_upload/main.tf
  deployment/src/main/terraform/modules/messaging/sources/storage_file_upload/variables.tf
  deployment/src/main/terraform/modules/messaging/variables.tf
  lambdas/trigger-resample-lambda/build.gradle.kts
  lambdas/trigger-resample-lambda/src/main/java/uk/gov/ukho/ais/triggerresamplelambda/TriggerResampleLambdaApplication.java
  lambdas/trigger-resample-lambda/src/main/java/uk/gov/ukho/ais/triggerresamplelambda/TriggerResampleLambdaHandler.java
  lambdas/trigger-resample-lambda/src/main/java/uk/gov/ukho/ais/triggerresamplelambda/configuration/ResampleLambdaConfiguration.java
  lambdas/trigger-resample-lambda/src/main/java/uk/gov/ukho/ais/triggerresamplelambda/function/TriggerResamplingFunction.java
  lambdas/trigger-resample-lambda/src/main/java/uk/gov/ukho/ais/triggerresamplelambda/messaging/SqsMessageRetriever.java
  lambdas/trigger-resample-lambda/src/main/java/uk/gov/ukho/ais/triggerresamplelambda/model/ResampleJobsSupplier.java
  lambdas/trigger-resample-lambda/src/main/java/uk/gov/ukho/ais/triggerresamplelambda/s3/BucketEmptier.java
  lambdas/trigger-resample-lambda/src/main/java/uk/gov/ukho/ais/triggerresamplelambda/service/ResamplingService.java
  lambdas/trigger-resample-lambda/src/main/java/uk/gov/ukho/ais/triggerresamplelambda/service/ResamplingServiceSupplier.java
  lambdas/trigger-resample-lambda/src/test/java/uk/gov/ukho/ais/triggerresamplelambda/TriggerResampleLambdaApplicationTest.java
  lambdas/trigger-resample-lambda/src/test/java/uk/gov/ukho/ais/triggerresamplelambda/function/TriggerResamplingFunctionTest.java
  lambdas/trigger-resample-lambda/src/test/java/uk/gov/ukho/ais/triggerresamplelambda/messaging/SqsMessageRetrieverTest.java
  lambdas/trigger-resample-lambda/src/test/java/uk/gov/ukho/ais/triggerresamplelambda/model/ResampleJobsSupplierTest.java
  lambdas/trigger-resample-lambda/src/test/java/uk/gov/ukho/ais/triggerresamplelambda/s3/BucketEmptierTest.java
  lambdas/trigger-resample-lambda/src/test/java/uk/gov/ukho/ais/triggerresamplelambda/service/ResamplingServiceTest.java
  lambdas/trigger-resample-lambda/src/test/resources/application.yml
  settings.gradle.kts
Labels: major, sprint related

#104 Process static data
  .flake8
  .gitignore
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  buildSrc/src/main/kotlin/uk/gov/ukho/gradle/plugin/python/PythonPlugin.kt
  deployment/build.gradle.kts
  deployment/src/main/terraform/main.tf
  deployment/src/main/terraform/modules/data-query/derived_resampled_100km_18hr_ais_table.tf
  deployment/src/main/terraform/modules/data-query/derived_resampled_30km_6hr_ais_table.tf
  deployment/src/main/terraform/modules/data-query/main.tf
  deployment/src/main/terraform/modules/data-query/osd_ais_table.tf
  deployment/src/main/terraform/modules/data-query/processed_ais_table.tf
  deployment/src/main/terraform/modules/data-query/processed_static_data_table.tf
  deployment/src/main/terraform/modules/data-query/variables.tf
  deployment/src/main/terraform/modules/functions/ais_raw_file_upload_function.tf
  deployment/src/main/terraform/modules/functions/ais_static_data_file_upload_function.tf
  deployment/src/main/terraform/modules/functions/all_heatmap_jobs_orchestration_function.tf
  deployment/src/main/terraform/modules/functions/function/main.tf
  deployment/src/main/terraform/modules/functions/function/variables.tf
  deployment/src/main/terraform/modules/functions/process_static_data_file_function.tf
  deployment/src/main/terraform/modules/functions/trigger_raw_partition_job.tf
  deployment/src/main/terraform/modules/functions/trigger_resample_function.tf
  deployment/src/main/terraform/modules/functions/variables.tf
  deployment/src/main/terraform/modules/storage/processed-static-data-store.tf
  deployment/src/main/terraform/modules/storage/variables.tf
  deployment/src/main/terraform/parameters.json.enc
  deployment/src/main/terraform/vars.tf
  lambdas/process_new_static_file/README.md
  lambdas/process_new_static_file/build.gradle.kts
  lambdas/process_new_static_file/requirements.txt
  lambdas/process_new_static_file/src/main/python/process_new_static_file/__init__.py
  lambdas/process_new_static_file/src/main/python/process_new_static_file/config.py
  lambdas/process_new_static_file/src/main/python/process_new_static_file/lambda_handler.py
  lambdas/process_new_static_file/src/main/python/process_new_static_file/new_static_file_handler.py
  lambdas/process_new_static_file/src/main/python/process_new_static_file/run_local.py
  lambdas/process_new_static_file/src/test/python/test_lambda_handler.py
  lambdas/process_new_static_file/src/test/python/test_new_static_file_handler.py
  settings.gradle.kts
  spark/libraries/ais-schemata/src/main/scala/uk/gov/ukho/ais/Schema.scala
Labels: enhancement, major, sprint related

#108 Change static file process lambda to python 3.7
  deployment/src/main/terraform/modules/functions/process_static_data_file_function.tf
Labels: bug, major, sprint related

#110 Add 'input_osd_static_data_file' column to static data table, schema
  deployment/src/main/terraform/modules/data-query/processed_static_data_table.tf
  spark/libraries/ais-schemata/src/main/scala/uk/gov/ukho/ais/Schema.scala
Labels: minor

#111 Bump jackson databind and add suppressions
  build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  dependency-suppressions.xml
Labels: minor

#112 Add monthly and season 100km18hr
  build.gradle.kts
  lambdas/ais-batch-lambda/src/main/java/uk/gov/ukho/aisbatchlambda/JobsProvider.java
  lambdas/ais-batch-lambda/src/test/java/uk/gov/ukho/aisbatchlambda/JobsProviderTest.java
Labels: sprint related
